config/routes.rb
Wikiful::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  get "welcome/index"

  root 'welcome#index'
  resources :articles
  resources :categories
  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :category_name, presence: true
	validates :category_name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles
	validates :name, :presence => true, :uniqueness => true
	validates :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  private
  def get_categories
    @categories = Category.all.order(:category_name)
  end

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
  	redirect_to login_path, alert: "You need to be logged in to do that" if current_user.nil?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 before_filter :authorize, only: [:new, :edit, :update]

  def index
  	@articles = Article.order(updated_at: :desc).limit(10)
  end

  def show
  	@article = Article.find(params[:id])
  end

  def new
  	@article = Article.new
  end

  def create
	@article = Article.new(article_params)
	if @article.save
		redirect_to @article
	else
		render "new"
	end
  end

  private
  	def article_params
  		params.require(:article).permit(:title, :content, :category_ids => [])
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all.order(:category_name)
  end

  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged In"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	@user = User.new
end

def create
	@user = User.new(user_params)
	if @user.save
		session[:user_id] = @user.id
		redirect_to root_url, notice: "Thanks for signing up."
	else
		render "new"
	end
end

private
	def user_params
		params.require(:user).permit(:email, :name, :password, :password_confirmation)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome_layout", only: :index

  def index
  	@recentart = Article.all.order(updated_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="control-group">
    <%= f.label :title %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content %>
    <div class="controls">
      <%= f.text_area :content, rows: "20", cols: "100" %>
    </div>
  </div>

  <div class="category-control">
    <%= f.label 'File under at least one category' %>
    <% Category.all.order(category_name: :asc).each do |category| %>
      <div>
        <%= check_box_tag "article[category_ids][]", category.id %>
        <%= category.category_name %>
      </div>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit nil %>
    <%= link_to 'Cancel', articles_path %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>The Most Recent Articles on Wikiful</h1><br>
<table class="table table-hover">
	<tr>
		<th>Article Title</th>
		<th>Date Created</th>
	</tr>
	<% @articles.each do |article| %>
	<tr>
		<td><%= link_to article.title.truncate(50), article %></h5></td>
		<td><%= article.created_at.strftime('%b. %d, %Y') %></td>
	</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
	<% if @article.errors.any? %>
	<div class="error_messages">
		<h2>You're missing some fields</h2>
		<ul>
			<% @article.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div>
	<h1><%= @article.title %>
		<small><br><%= @article.created_at.strftime('%b. %d, %Y') %></small></h1>
	<div><%= simple_format(@article.content) %></div>
	<p class="lead">Filed under: <strong><% @article.categories.each do |category| %>
			<%= link_to category.category_name, category %></strong>&nbsp;
		<% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories on Wikiful</h1>
<ul>
<% @categories.each do |category| %>
	<div>
		<li><h3><%= link_to category.category_name, category %></h3></li>
	</div>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.category_name %></h1><br>
	<table class="table table-hover">
		<tr>
			<th>Article Title</th>
			<th>Date Created</th>
		</tr>
	<% @category.articles.each do |article| %>
		<tr>
			<td><%= link_to article.title.truncate(50), article %></h5></td>
			<td><%= article.created_at.strftime('%b. %d, %Y') %></td>
		</tr>
	<% end %>
	</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  <!--[if lt IE 9]> <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Wikiful", root_path, :class => "brand" %>
      	<ul class="nav navbar-nav">
      		<li><%= link_to "Articles", articles_path, :class =>"active" %></li>
      		<li><%= link_to "Categories", categories_path, :class =>"active" %></li>
  	  	</ul>
  	  	<div class="session-controls" style="float: right">
  	  			<% if current_user %>
  	  				<%= link_to "Log Out", logout_path, :class => "btn btn-mini navbar-btn" %>
  	  				Logged in as <%= current_user.email %>
  	  			<% else %>
  	  			<div class="btn-group">
  	  			<%= link_to "Sign Up", signup_path, :class => "btn btn-mini navbar-btn" %>
  	  			<%= link_to "Log In", login_path, :class => "btn btn-mini navbar-btn" %>
  	  			</div>
  	  			<% end %>
  	  	</div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
  	<div class="span4">
  		<% flash.each do |name, msg| %>
  		<%= content_tag :div, msg, id:"flash_#{name}" %>
  		<% end %>
  	</div>
  </div>
  <div class="row">
    <div class="span9"><div style="padding: 0x 10px 0x 0x"><%= yield %></div></div>
    <div class="span3 sidebar">
	  <div class="my-wiki-site">
	    <h4>Wikiful</h4>
	    <ul>
	    <li><%= link_to "Write a Wiki", new_article_path %></li>
	    </ul>
	  </div>
	  <div class="categories-sidebar">
	    <h4>Categories</h4>
	    <ul>
	      <% @categories.each do |category| %>
	        <li><%= link_to category.category_name, category %></li>
	      <% end %>
	    </ul>
	  </div>
	  <div class="about">
	    <h4>About Wikiful</h4>
	    <p>Wikiful was built so that Bharat could learn Ruby.</p>
	  </div>
	</div>
  </div>
</div>
</body>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  <!--[if lt IE 9]> <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Wikiful", root_path, :class => "brand" %>
      <ul class="nav navbar-nav">
      		<li><%= link_to "Articles", articles_path, :class => "active" %></li>
      		<li><%= link_to "Categories", categories_path, :class => "active" %></li>
  	  	</ul>
      <div class="session-controls" style="float: right">
            <% if current_user %>
              <%= link_to "Log Out", logout_path, :class => "btn btn-mini navbar-btn" %>
              Logged in as <%= current_user.email %>
            <% else %>
            <div class="btn-group">
            <%= link_to "Sign Up", signup_path, :class => "btn btn-mini navbar-btn" %>
            <%= link_to "Log In", login_path, :class => "btn btn-mini navbar-btn" %>
            </div>
            <% end %>
        </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span4">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id:"flash_#{name}" %>
      <% end %>
    </div>
  </div>
<div class="jumbotron">
		<h1>Welcome to Wikiful<br>
			<small>A Thinkful Project</small></h1>
	</div>
<div class ="row" style="padding: 15px">
		<%= yield %>
</div>
</div>
</div>
</body>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %> 
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %> 
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %> 
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> 
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<div class ="col-lg-12">
<center><h3>Recent Articles</h3></center>
<table class="table table-hover">
<tr>
<% @recentart.each do |recentart| %>
	<td><h4>
		<%= link_to recentart.title.truncate(60), recentart %>
		<small>(<%= recentart.created_at.strftime('%b. %d, %Y') %>)</small>
	</h4></td>
</tr>
<tr>
	<td><%= recentart.content.truncate(250) %> ... <%= link_to "Read More", recentart %>
	</tr>
<% end %>
</tr>
</table>
</div>